title: "Phòng khám Sản Phụ khoa Bình Minh"
description: "Bài viết kiến thức sản phụ khoa bởi BS CKII Lê Đàm Vân – Bệnh viện Từ Dũ"

url: "https://vutienluc178.github.io"
baseurl: "/SPK"   # ví dụ: /clinic-binhminh
logo: /assets/img/og-cover.jpg

theme: null
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "BS CKII Lê Đàm Vân"
  url: "/"
  email: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "BS CKII Lê Đàm Vân"
      image: "/assets/img/og-cover.jpg"
      lang: "vi"
